Name = "Rain Cloud DNS"
Description = ''''''
URL = "https://api.v2.rainyun.com/product/domain"
Code = "raindns"
Since = "v1.0.0"

Example = '''
# using credentials
RAIN_API_KEY=abcdefghijklmnopqrstuvwx \
lego --email you@example.com --dns raindns - -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    RAIN_API_KEY = "Access key ID"
  [Configuration.Additional]
    RAIN_POLLING_INTERVAL = "Time between DNS propagation check"
    RAIN_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    RAIN_TTL = "The TTL of the TXT record used for the DNS challenge"
    RAIN_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://www.apifox.cn/apidoc/shared-a4595cc8-44c5-4678-a2a3-eed7738dab03"
